# Generated by Django 4.2.11 on 2024-08-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_data', '0002_article_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
